name: Sim merge tests

on: [pull_request, push]

jobs:
  kurtosis:
    name: kurtosis
    runs-on: ubuntu-latest
    # Increase timeout if we add more difficult tests that take longer!
    timeout-minutes: 10
    steps:
      - name: Checkout this repo
        uses: actions/checkout@master
      - name: Update kurtosis to latest and set metrics choice
        shell: bash
        run: |
            echo "deb [trusted=yes] https://apt.fury.io/kurtosis-tech/ /" | sudo tee /etc/apt/sources.list.d/kurtosis.list
            sudo apt update
            sudo apt install kurtosis-cli -y
            kurtosis config init dont-send-metrics
            
      - name: Render Deployment YAML
        uses: nowactions/envsubst@v1
        with:
          input: ./kurtosis/config.json.tmpl
          output: ./config.json
        env:
          TEKU_IMAGE: "consensys/teku"
          NIMBUS_IMAGE: "parithoshj/nimbus"
          PRYSM_BEACON_IMAGE: "gcr.io/prysmaticlabs/prysm/beacon-chain"
          PRYSM_VALIDATOR_IMAGE: "gcr.io/prysmaticlabs/prysm/validator"
          LIGHTHOUSE_IMAGE: "sigp/lighthouse:latest-unstable"
          LODESTAR_IMAGE: "chainsafe/lodestar:next"
          GETH_IMAGE: "parithoshj/geth:master"
          NETHERMIND_IMAGE: "nethermindeth/nethermind"
      - name: Run kurtosis with the config
        run: kurtosis module exec --enclave-id newname kurtosistech/eth2-merge-kurtosis-module  --execute-params "$(cat ./config.json)"
      - name: Run kurtosis with the config
        if: always()
        run: kurtosis enclave dump newname dumped_logs
      - uses: actions/upload-artifact@v2
        if: always()
        with:
          name: dumped_logs
          path: ./dumped_logs
  cleanup:
    runs-on: kurtosis
    needs: [kurtosis]
    if: always()
    steps:
      - name: Cleanup
        run: kurtosis enclave rm newname --force
