name: Sim merge tests

on: [pull_request, push]

env:
    TEKU_IMAGE: "consensys/teku"
    NIMBUS_IMAGE: "parithoshj/nimbus"
    PRYSM_BEACON_IMAGE: "gcr.io/prysmaticlabs/prysm/beacon-chain"
    PRYSM_VALIDATOR_IMAGE: "gcr.io/prysmaticlabs/prysm/validator"
    LIGHTHOUSE_IMAGE: "sigp/lighthouse:latest-unstable"
    LODESTAR_IMAGE: "chainsafe/lodestar:next"
    GETH_IMAGE: "g11tech/geth:kilnv1"
    NETHERMIND_IMAGE: "nethermindeth/nethermind"
jobs:
  kurtosis:
    name: kurtosis
    runs-on: kurtosis
    # Increase timeout if we add more difficult tests that take longer!
    timeout-minutes: 10
    steps:
      - name: Checkout this repo
        uses: actions/checkout@master
      - name: Update kurtosis to latest and set metrics choice
        shell: bash
        run: |
            sudo apt update
            sudo apt upgrade kurtosis-cli