name: Release
on: [push, pull_request]
jobs:
  tag:
    name: Check and Tag
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: Get tag
        id: get_tag
        run: echo ::set-output name=tag::${GITHUB_REF/refs\/tags\//}
      - name: Get previous tag
        id: get_prev_tag
        run: $(node scripts/get_prev_tag.js)
        env:
          CURRENT_TAG: ${{ steps.get_tag.outputs.tag }}
          IGNORE_PATTERN: beta
    outputs:
      is_beta: ${{ contains(github.ref, 'beta') }}
      tag: ${{ steps.get_tag.outputs.tag }}
      prev_tag: ${{ steps.get_prev_tag.outputs.prev_tag }}
      version: ${{ steps.get_version.outputs.version }}

  job2:
    runs-on: ubuntu-latest
    needs: tag
    steps:
    - run: echo ${{needs.tag.outputs.tag}} ${{needs.tag.outputs.prev_tag}}
    - uses: actions/setup-node@v1
      with:
        tagtest: ${{ needs.tag.outputs.tag }}
        prevtagtest: ${{ needs.tag.outputs.prev_tag }}
